#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#runApplication -s "columnAverage" postProcess -func columnAverage

#------------------------------------------------------------------------------


