#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

python3 createMesh.py

touch case.foam

runApplication blockMesh

runApplication $(getApplication)

#------------------------------------------------------------------------------
