#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cleanCase0

restore0Dir

touch case.foam

blockMesh
pbtesFoam

# runApplication blockMesh

# runApplication $(getApplication)

#------------------------------------------------------------------------------
