#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# setups="
# cylinder
# cylinder_1d
# "

setups="
cylinder_1d
"

# flags to enable setup and computations
setup_flag=true
run_flag=true

# flag to enable computations in parallel mode
parallel=false

#------------------------------------------------------------------------------

case_setup() {

    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }

    setup="$1"
    dirSetup="setups/$setup"
    dirSetupOrig="setups.orig/$setup"
    dirOrig="$dirSetupOrig/0.orig"
    dirConstant="$dirSetupOrig/constant"
    dirSystem="$dirSetupOrig/system"

    printf "# Currently processing: %s\n" "$setup"

    if [ ! -d "$dirSetup" ]
    then
        printf "      # Creating directory: %s\n" "$dirSetup"    
        mkdir -p "$dirSetup"

        cp -aRfL "setups.orig/common/." "$dirSetup"
        cp -afL "$dirSetupOrig"/All* "$dirSetup" 2>/dev/null || :
        [ -d "$dirOrig" ] && cp -aRfL "$dirOrig/." "$dirSetup/0.orig"
        [ -d "$dirConstant" ] && cp -aRfL "$dirConstant/." "$dirSetup/constant"
        [ -d "$dirSystem" ] && cp -aRfL "$dirSystem/." "$dirSetup/system"
    else
        printf "      # Directory %s already exists\n" "$dirSetup"
        printf "      # Skipping the creation of directory\n"
    fi
}

case_run() {

    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }

    setup="$1"
    dirSetup="setups/$setup"
    dirResult="results/$setup"

    dry_run_setup "$setup"
    [ -d results ] || mkdir -p results

    printf "\n# Run the setup: %s\n\n" "$setup"

    if [ ! -d "$dirResult" ]
    then
        cp -Rf "$dirSetup" "$dirResult"

        if [ "$parallel" = true ]
        then
            ( cd "$dirResult" && ./Allrun-parallel )
        else
            ( cd "$dirResult" && ./Allrun )
        fi

    else
        printf "      # Directory %s already exists\n" "$dirResult"
        printf "      # Skipping the computation of the given setup\n"
    fi
}


#------------------------------------------------------------------------------

for setup in $setups

do
    dirSetupOrig="setups.orig/$setup"

    if [ ! -d "$dirSetupOrig" ]
    then
        echo "Setup directory: $dirSetupOrig" \
             "could not be found - skipping execution" 1>&2
        continue
    fi

    if [ "$setup_flag" = true ]
    then
        case_setup "$setup"
    fi

    if [ "$run_flag" = true ]
    then
        case_run "$setup"
    fi
done


if notTest "$@" && [ "$run" = true ]
then
    ./plot
fi

#------------------------------------------------------------------------------